### ISSUE TITLE
sonar ignoring openclover test coverage results

### ISSUE THREAD

**Issue by andyglick** [Tony-Proum/sonar-clover#10]
Hello, I have been using sonarcloud on-line and for the most part am very happy with your service, however I have been unable to figure out how to get the sonar scanner for maven to make use of the clover coverage information that I am producing with the new openclover maven plugin. I have added the sonar-clover jar as a dependency of the sonar-maven-plugin, and I have configured the sonar-clover jar as a project dependency. In no case does the sonar-maven-plugin report any clover coverage information.

If you could explain:

1) should I expect the sonar-maven to work, or is it broken? 

2) if it ought to be working could you provide an example that covers the necessary configuration details?

org.openclover:clover-maven-plugin:jar:4.2.0
org.sonarsource.scanner.maven:sonar-maven-plugin:jar:3.3.0.603 

I have been following the directions that I found at the github sonar-clover site and have been setting the system property sonar.clover.reportPath to the location of the generated clover report as called out at the URL listed below

https://github.com/SonarQubeCommunity/sonar-clover

**Comment by mlschechter** [comment]
If you're using a SonarQube instance at 6.x or later, this should be addressed by my [pull request](https://github.com/Tony-Proum/sonar-clover/pull/15). Please let me know if you have any questions.

**Comment by Tony-Proum** [comment]
Hi,
sonar-clover plugin is a community plugin, it is not maintained by SonarSource, also it seems like only SonarSource's plugins are installed on Sonarcloud

**Comment by Tony-Proum** [comment]
In order to use this plugin, you could install your own sonarqube instance, this way, you should be able to manage which plugin you want to use
